# Use postgres/example user/password credentials
#localhost:5432/postgres-postgres-postgres
version: '3.1'

services:

  flask:
    image: flask
    environment:
      PORT: "8080"

    ports:
      - 8080:8080

#docker-compose up
